# Generated by Django 3.1.3 on 2020-12-01 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_auto_20201130_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Published'),
        ),
    ]
