# Generated by Django 3.1.3 on 2020-12-01 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_artifact_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='artifact_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date Published'),
        ),
    ]
