# Generated by Django 3.1.3 on 2020-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_auto_20201201_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='discovered_by',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
