# Generated by Django 3.1.3 on 2020-12-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0007_auto_20201201_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.ImageField(default='userimages/qmark.png', upload_to='userimages'),
        ),
    ]
