# Generated by Django 3.1.3 on 2020-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0010_auto_20201201_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(default='artifacts/uploads/qmark.png', upload_to='artifacts/uploads'),
        ),
    ]
