# Generated by Django 3.1.3 on 2020-12-01 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0011_auto_20201201_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Published'),
        ),
    ]
