# Generated by Django 3.1.3 on 2020-12-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0012_auto_20201201_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='artifact',
        ),
        migrations.AddField(
            model_name='artifact',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artifacts.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default='artifacts/uploads/qmark.png', upload_to='artifacts/uploads'),
        ),
    ]
